DIM_CALENDAR = 
CREATE TABLE IF NOT EXISTS DIM_CALENDAR(
    PK_DATE INT PRIMARY KEY,
    DATA DATE,
    YEAR INT
)

DIM_USERS =
CREATE TABLE IF NOT EXISTS DIM_USERS(
    PK_USERS INT PRIMARY KEY,
    CD_USERS VARCHAR(12)
)


DIM_MOTIVO_LEITURA =
CREATE TABLE IF NOT EXISTS DIM_MOTIVO_LEITURA (
    CD_MOTIVO_LEITURA VARCHAR(2),
    SK_MOTIVO_LEITURA BIGINT NOT NULL,
    INDEX idx_SK_MOTIVO_LEITURA (SK_MOTIVO_LEITURA)
)


DIM_STATUS_LEITURA =
CREATE TABLE IF NOT EXISTS DIM_STATUS_LEITURA (
    CD_STATUS_LEITURA VARCHAR(1),
    SK_STATUS_LEITURA BIGINT,
    INDEX idx_SK_STATUS_LEITURA (SK_STATUS_LEITURA)
)


DIM_MEDIDOR = 
CREATE TABLE IF NOT EXISTS DIM_MEDIDOR (
    CD_MEDIDOR VARCHAR(18) PRIMARY KEY,
    SK_MEDIDOR BIGINT NOT NULL,
    NR_SERIE_MEDIDOR VARCHAR(18) NOT NULL,
    CD_LOCAL_INSTALACAO VARCHAR(18),
    DS_FABRICANTE VARCHAR(30),
    DS_MEDIDOR VARCHAR(45),
    DT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_SK_MEDIDOR (SK_MEDIDOR)
    )


DIM_MERCADO =
CREATE TABLE IF NOT EXISTS DIM_MERCADO (
    CD_SEGMENTO_MERCADO VARCHAR(50) PRIMARY KEY,
    SK_SEGMENTO_MERCADO BIGINT NOT NULL,
    DS_SEGMENTO_MERCADO VARCHAR(255),
    DT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_SK_SEGMENTO_MERCADO (SK_SEGMENTO_MERCADO)
    )


FATO_LEITURA =
CREATE TABLE IF NOT EXISTS FATO_LEITURA (
    CD_DOCUMENTO_LEITURA VARCHAR(20) PRIMARY KEY,
    SK_MEDIDOR BIGINT NOT NULL,
    SK_SEGMENTO_MERCADO BIGINT NOT NULL,
    SK_INSTALACAO BIGINT NOT NULL,
    SK_MOTIVO_LEITURA BIGINT NOT NULL,
    SK_NOTA_LEITURISTA BIGINT,
    SK_STATUS_LEITURA BIGINT,
    CD_ADICIONADO_POR INT,
    CD_MODIFICADO_POR INT,
    CD_REGISTRADOR VARCHAR(3),
    VL_LEITURA_ATUAL DECIMAL(45,18),
    VL_LEITURA_ANTERIOR DECIMAL(45,18),
    VL_LEITURA_PERIODO_ANTERIOR DECIMAL(45,18),
    DT_LEITURA INT,
    DT_LEITURA_PREVISTA INT,
    DT_MODIFICACAO INT,
    DT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SK_MEDIDOR) REFERENCES DIM_MEDIDOR(SK_MEDIDOR),
    FOREIGN KEY (SK_SEGMENTO_MERCADO) REFERENCES DIM_MERCADO(SK_SEGMENTO_MERCADO),
    FOREIGN KEY (SK_MOTIVO_LEITURA) REFERENCES DIM_MOTIVO_LEITURA(SK_MOTIVO_LEITURA),
    FOREIGN KEY (SK_STATUS_LEITURA) REFERENCES DIM_STATUS_LEITURA(SK_STATUS_LEITURA),
    FOREIGN KEY (DT_LEITURA) REFERENCES DIM_CALENDAR(PK_DATE),
    FOREIGN KEY (DT_LEITURA_PREVISTA) REFERENCES DIM_CALENDAR(PK_DATE),
    FOREIGN KEY (DT_MODIFICACAO) REFERENCES DIM_CALENDAR(PK_DATE),
    FOREIGN KEY (CD_ADICIONADO_POR) REFERENCES DIM_USERS(PK_USERS),
    FOREIGN KEY (CD_MODIFICADO_POR) REFERENCES DIM_USERS(PK_USERS)
    )